config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'admin/homes#top'
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:edit, :update, :index, :new, :create, :show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get 'sessions/new'
    get 'homes/top'
    patch '/admin/ordered_itmes/:id'=>'ordered_items#update'
  end
  scope module: :public do
    get 'homes/top'
    get 'homes/about'
    get '/orders/complete' => 'orders#complete', as: 'complete'
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    resource :customer
    resources :deliveries, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create]
    delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
    get 'customer/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customer/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
end
  root to: 'public/homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :addresses
  has_many :cart_items

  def active_for_authentication?
     super && (is_active == true)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  def update
    @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  else
    render :edit
  end
  end

private
 def customer_params
  params.require(:customer).permit(:email, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number,:is_active)
 end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name, :last_name_kana, :first_name, :first_name_kana, :address, :telephone_number, :postal_code])
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-4"></div>
<h3><%= @customer.first_name %><%= @customer.last_name %>の会員情報編集</h3>
</div>
</div>
<%= form_with model: @customer,url: admin_customer_path, local: true do |f| %>
<div class="container">
<div class="row">
<div class ="col-ml-6"></div>
<table width="50%">
<tbody>
<tr>
<td>会員ID</td>
<td><%= @customer.id %></td>
</tr>
<tr>
<td>氏名</td>
<td><%= f.text_field :first_name %></td><td><%= f.text_field :last_name %></td>
</tr>
<tr>
<td>フリガナ</td>
<td><%= f.text_field :first_name_kana %></td><td><%= f.text_field :last_name_kana %></td>
</tr>
<tr>
<td>郵便番号</td>
<td><%= f.text_field :postal_code %></td>
</tr>
<tr>
<td>住所</td>
<td><%= f.text_field :address %></td>
</tr>
<tr>
<td>電話番号</td>
<td><%= f.text_field :telephone_number %></td>
</tr>
<tr>
<td>メールアドレス</td>
<td><%= f.text_field :email %></td>
</tr>
<tr>
<td>会員ステータス</td>
<td>
<%= f.label :is_active, '有効', value: true %>
<%= f.radio_button :is_active, :true %>
<%= f.label :is_active, '退会', value: false %>
<%= f.radio_button :is_active, :false %>
</td>
</tr>
<tr>
<td>
<input class="btn btn-success" type="submit" value= "変更を保存">
<% end %>
</td>
</tr>
</tbody>
</table>
</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-4"></div>
<h3>会員一覧</h3>
</div>
</div>
<div class="container">
<div class="row">
<div class ="col-ml-6"></div>
<table width="80%">
<tbody>
<tr>
<th>会員ID</th>
<th>氏名</th>
<th>メールアドレス</th>
<th>ステータス</th>
</tr>
<% @customers.each do |customer| %>
<tr>
<td><%= customer.id %></td>
<td><%= link_to admin_customer_path(customer.id) do %>
<%= customer.first_name %>
<%= customer.last_name %>
<% end %>
</td>
<td><%= customer.email %></td>
<td>
<% if customer.is_active == true %>
<div class="text-success">有効</div>
<% else %>
<div class="text-secondary">退会</div>
<% end %>
</td>
<% end %>
</tr>
</tbody>
</table>
</div>
</div>
<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-4"></div>
<h3><%= @customer.first_name %><%= @customer.last_name %>の会員詳細</h3>
</div>
</div>
<div class="container">
<div class="row">
<div class ="col-ml-6"></div>
<table width="30%">
<tbody>
<tr>
<td>会員ID</td>
<td><%= @customer.id %></td>
</tr>
<tr>
<td>氏名</td>
<td><%= @customer.first_name %><%= @customer.last_name %></td>
</tr>
<tr>
<td>フリガナ</td>
<td><%= @customer.first_name_kana %><space><%= @customer.last_name_kana %></space></td>
</tr>
<tr>
<td>郵便番号</td>
<td><%= @customer.postal_code %></td>
</tr>
<tr>
<td>住所</td>
<td><%= @customer.address %></td>
</tr>
<tr>
<td>電話番号</td>
<td><%= @customer.telephone_number %></td>
</tr>
<tr>
<td>メールアドレス</td>
<td><%= @customer.email %></td>
</tr>
<tr>
<td>会員ステータス</td>
<td>
<% if @customer.is_active == true %>
<div class="text-success">有効</div>
<% else %>
<div class="text-secondary">退会</div>
<% end %>
</td>
</tr>
<div class="container">
<div class="row">
<div class ="col-ml-6"></div>
<tr>
<td>
<%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
</td>
<td>
<%= link_to '注文履歴一覧を見る',admin_orders_path, class: "btn btn-primary" %>
</td>
</tr>
</div>
</div>
</tbody>
</table>
</div>
</div>