config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'admin/homes#top'
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:edit, :update, :index, :new, :create, :show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get 'sessions/new'
    get 'homes/top'
    patch '/admin/ordered_itmes/:id'=>'ordered_items#update'
  end
  scope module: :public do
    get 'homes/top'
    get 'homes/about'
    get '/orders/complete' => 'orders#complete', as: 'complete'
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    resource :customer
    resources :deliveries, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create]
    delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
    get 'customer/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customer/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
end
  root to: 'public/homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + resident + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.add_tax_price*amount
  end
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :addresses
  has_many :cart_items

  def active_for_authentication?
     super && (is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_one_attached :image
    has_many :items
end

app/models/home.rb
class Home < ApplicationRecord

    has_one_attached :image
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :ordered_items
  has_many :cart_items
  has_one_attached :image

def add_tax_price
    (price*1.10).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :ordered_items
  belongs_to :customer
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  def create
    @genre = Genre.new(genre_params)
  if @genre.save
    redirect_to admin_genres_path
  else
   @genres = Genre.all
   render:index
  end

  end

  def edit
   @genre = Genre.find(params[:id])
  end
  def update
     @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
    redirect_to admin_genres_path
  else
    render :edit
  end
  end
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def index
    @item = Item.new
    @items = Item.page(params[:page])
    @genres = Genre.all
  end
  def create
     @item = Item.new(item_params)
  if @item.save
    redirect_to admin_item_path(@item.id)
  else
    @items = Item.page(params[:page])
    render :index
  end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  def update
    @item = Item.find(params[:id])
  if @item.update(item_params)
   redirect_to admin_item_path(@item.id)
  else
   @genres = Genre.all
   render :edit
  end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/ordered_items_helper.rb
module Admin::OrderedItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-4"></div>
<h3>ジャンル編集</h3>
<%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
</div>
</div>
<div class="container">
<div class="row">
<div class ="col-ml-4"></div>
<table width="50%">
<tbody>
<tr>
<th>
ジャンル名
</th>
<td>
<%= f.text_field :name %>
</td>
<td>
<input class="btn btn-success" type="submit" value="変更を保存">
<% end %>
</td>
</tr>
</tbody>
</table>
<table>
</div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-4"></div>
<h3>ジャンル一覧・追加</h3>
</div>
</div>

<div class="container">
<div class="row">
<div class ="col-ml-4"></div>
<%= form_with model: @genre,url: admin_genres_path, local: true do |f| %>
<table>
<tbody>
<tr>
<th>
ジャンル名
</th>
<td>
<%= f.text_field :name %>
</td>
<td>
 <input class="btn btn-success" type="submit" value="新規登録">
<% end %>
</td>
</tr>
</tbody>
</table>
</div>
</div>

<div class="container">
<div class="row">
<div class ="col-m-4"></div>
<table width="50%">
<tbody>
<tr>
<th>
ジャンル
</th>
</tr>

<% @genres.each do |genre| %>
<tr>
<td>
<%= genre.name %>
</td>
<td>
<%= link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-success" %>
</td>
<% end %>
</tr>
</tbody>
</table>
</div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-4"></div>
<h3>注文履歴一覧</h3>
</div>
</div>
<div class="container">
<div class="row">
<div class ="col-ml-6"></div>
<table width="50%">
<tbody>
<tr>
<th>購入日時</th>
<th>購入者</th>
<th>注文個数</th>
</tr>
<% @orders.each do |order| %>
<tr>
<td>
<%= link_to admin_order_path(order.id) do %>
<%= order.created_at %>
<% end %>  
</td>
<td><%= order.customer.first_name %>
    <%= order.customer.last_name %>
</td>
<td></td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
<%= paginate @orders %>

app/views/admin/items/edit.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-2"></div>
<h3>商品編集</h3>
</div>
</div>

<div class="container">
<div class="row">
<div class ="col-ml-"></div>
<%= form_with model: @item, url: admin_item_path, local: true do |f| %>
<table>
<tbody>
<tr>
<td>
商品画像
</td>
<td>
<%= f.file_field :image, placeholder: "商品画像", accept: "image/*" %>
</td>
</tr>
<tr>
<td>
商品名
</td>
<td>
<%= f.text_field :name %>
</td>
</tr>
<tr>
<td>
商品説明
</td>
<td>
<%= f.text_area :introduction %>
</td>
</tr>
<tr>
<td>
ジャンル
</td>
<td>
<%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "選択してください"}) %>
</td>
</tr>
<tr>
<td>
税抜価格
</td>
<td>
<%= f.text_field :price, placeholder: "1000" %>円
</td>
</tr>
<tr>
<td>
販売ステータス
</td>
<td>
<%= f.label :is_active, '販売中', value: true %>
<%= f.radio_button :is_active, :true %>
<%= f.label :is_active, '販売停止中', value: false %>
<%= f.radio_button :is_active, :false %>
</td>
</tr>
<tr>
<td>
<input class="btn btn-success" type="submit" value="変更を保存">
<% end %>
</td>
</tr>
</tbody>
</table>
</div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-6 mt-3">
<table width="120%">
<tbody>
<tr>
<th>
商品一覧
</th>
</tr>
<tr>
<td>商品ID</td>
<td>商品名</td>
<td>税抜き価格</td>
<td>ジャンル</td>
<td>ステータス</td>
</tr>
<% @items.each do |item| %>
<tr>
<td><%= item.id %></td>
<td><%= link_to admin_item_path(item.id) do %>
<%= item.name %>
<% end %>
</td>
<td><%= item.price %></td>
<td><%= item.genre.name %></td>
<td>
<% if item.is_active == true %>
<div class="text-success">販売中</div>
<% else %>
<div class="text-secondary">販売停止中</div>
<% end %>
</td>
<% end %>
</tr>
</tbody>
</table>
</div>
<div class ="col-ml-6">
<%= link_to "+" , new_admin_item_path, class: 'btn btn-outline-dark' %>
</div>
</div>
</div>
<%= paginate @items %>

app/views/admin/items/new.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-4"></div>
<table>
<tbody>
<tr>
<th>
商品新規登録
</th>
<%= form_with model: @item,url: admin_items_path, local: true do |f| %>
<tr>
<td>
商品画像
</td>
<td>
<%= f.file_field :image, placeholder: "商品画像", accept: "image/*" %>
</td>
</tr>
<tr>
<td>
商品名
</td>
<td>
<%= f.text_field :name %>
</td>
</tr>
<tr>
<td>
商品説明
</td>
<td>
<%= f.text_area :introduction %>
</td>
</tr>
<tr>
<td>
ジャンル
</td>
<td>
<%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "選択してください"}) %>
</td>
</tr>
<tr>
<td>
税抜価格
</td>
<td>
<%= f.text_field :price, placeholder: "1000" %>円
</td>
</tr>
<tr>
<td>
販売ステータス
</td>
<td>
<%= f.label :is_active, '販売中', value: true %>
<%= f.radio_button :is_active, '販売中' %>
<%= f.label :is_active, '販売停止中', value: false %>
<%= f.radio_button :is_active, '販売停止中' %>
</td>
</tr>
<tr>
<td>
<input class="btn btn-success" type="submit" value="新規登録">
</td>
</tr>
</tbody>
</table>
<% end %>
</div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
<div class="row">
<div class ="col-ml-2"></div>
<h3>商品詳細</h3>
</div>
</div>
<div class="container">
<div class="row">
<div class ="col-lg-4">
<% if @item.image.attached? %>
<%= image_tag @item.image, size: "300x300" %>
<% else %>
<%= image_tag '/assets/no_image.jpg', size: "300x300" %>
<% end %>
</div>

<div class ="col-lg-8">
<table>
<tbody>
<tr>
<td>商品名</td>
<td>
<%= @item.name %>
</td>
</tr>
<tr>
<td>商品説明</td>
<td><%= @item.introduction %></td>
</tr>
<tr>
<td>ジャンル</td>
<td><%= @item.genre.name %></td>
</tr>
<tr>
<td>税込価格</br>（税抜価格）</td>
<td>
<%= @item.add_tax_price %>(<%= @item.price %>)円
</td>
</tr>
<tr>
<td>ステータス</td>
<td>
<% if @item.is_active == true %>
<div class="text-success">販売中</div>
<% else %>
<div class="text-secondary">販売停止中</div>
<% end %>
</td>
</tr>
<tr>
<td>
<%= link_to "編集する",edit_admin_item_path(@item.id), class: "btn btn-success" %>
</td>
</tr>
</tbody>
</table>
</div>