config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'admin/homes#top'
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:edit, :update, :index, :new, :create, :show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get 'sessions/new'
    get 'homes/top'
    patch '/admin/ordered_itmes/:id'=>'ordered_items#update'
  end
  scope module: :public do
    get 'homes/top'
    get 'homes/about'
    get '/orders/complete' => 'orders#complete', as: 'complete'
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    resource :customer
    resources :deliveries, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create]
    delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
    get 'customer/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customer/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
end
  root to: 'public/homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + resident + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.add_tax_price*amount
  end
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :addresses
  has_many :cart_items

  def active_for_authentication?
     super && (is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_one_attached :image
    has_many :items
end

app/models/home.rb
class Home < ApplicationRecord

    has_one_attached :image
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :ordered_items
  has_many :cart_items
  has_one_attached :image

def add_tax_price
    (price*1.10).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :ordered_items
  belongs_to :customer
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: message_type %>
    <% end %>
    <header class = "bg-white">
    <nav class = "navbar">
    <% if customer_signed_in? %>

   <h3 class="me-auto p-2 bd-highlight border border-dark">Nagano_Cake</h3>
   <div class="d-flex justify-content-end">
   <div class="p-2 bd-highlight">
      <%= link_to customer_path,class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">マイページ</button>
      <% end %>
   </div>

    <div class="p-2 bd-highlight">
      <%= link_to items_path,class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">商品一覧</button>
      <% end %>
    </div>

    <div class="p-2 bd-highlight">
      <%= link_to cart_items_path, class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">カート</button>
      <% end %>
    </div>

    <div class="p-2 bd-highlight">
      <%= link_to destroy_customer_session_path, method: :delete, class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">ログアウト</button>
      <% end %>
    </div>
    </div>
    </div>
    <% elsif admin_signed_in? %>

    <h3 class="me-auto p-2 bd-highlight border border-dark">Nagano_Cake</h3>

    <div class="d-flex justify-content-end">

    <div class="p-2 bd-highlight">
      <%= link_to admin_items_path,class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">商品一覧</button>
      <% end %>
    </div>
    <div class="p-2 bd-highlight">
      <%= link_to admin_customers_path,class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">会員一覧</button>
      <% end %>
    </div>
    <div class="p-2 bd-highlight">
      <%= link_to admin_orders_path,class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">注文履歴一覧</button>
      <% end %>
    </div>
    <div class="p-2 bd-highlight">
       <%= link_to admin_genres_path,class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">ジャンル一覧</button>
      <% end %>
    </div>
    <div class="p-2 bd-highlight">
      <%= link_to destroy_admin_session_path, method: :delete, class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">ログアウト</button>
      <% end %>
    </div>
    </div>
    <% else %>

    <h3 class="me-auto p-2 bd-highlight border border-dark">Nagano_Cake</h3>

    <div class="d-flex justify-content-end">
    <div class="p-2 bd-highlight">
      <%= link_to "/homes/about",class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">About</button>
      <% end %>
    </div>
    <div class="p-2 bd-highlight">
      <%= link_to items_path,class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">商品一覧</button>
      <% end %>
    </div>
    <div class="p-2 bd-highlight">
      <%= link_to "/customers/sign_up",class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">新規登録</button>
      <% end %>
    </div>
    <div class="p-2 bd-highlight">
      <%= link_to new_customer_session_path,class:"text-dark" do %>
      <button type="button" class="btn btn-outline-dark">ログイン</button>
      <% end %>
    </div>
    </div>
    <% end %>
    </nav>
    </nav>


    </header>
    </div>
    <%= yield %>
  </body>
</html>